/*
Copyright 2020 RS4
@Author: Weny Xu
@Date: 2021/01/10 18:04
*/

package entity

type AlipayOpenAuthTokenApp struct {
	Common          `json:",inline"`
	UserID          string `json:"user_id"`
	AuthAppID       string `json:"auth_app_id"`
	AppAuthToken    string `json:"app_auth_token"`
	AppRefreshToken string `json:"app_refresh_token"`
	ExpiresIn       string `json:"expires_in"`
	ReExpiresIn     string `json:"re_expires_in"`
}

type AutoGenerated struct {
	AlipayOpenAuthTokenApp `json:"alipay_open_auth_token_app_response"`
	Sign                   string `json:"sign"`
}
